version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_DATABASE=website_search
      - DB_USERNAME=root
      - DB_PASSWORD=
      - SCOUT_DRIVER=database
      - SCOUT_QUEUE=true
      - QUEUE_CONNECTION=redis
      - REDIS_HOST=redis
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=website_search
    ports:
      - "3306:3306"
  redis:
    image: redis:6
    ports:
      - "6379:6379"